site_name: RegReplace Documentation
repo_url: https://github.com/facelessuser/RegReplace
site_description: A Sublime Text plugin for creating regex sequences.
copyright: Copyright &copy; 2011 - 2017 <a href="https://github.com/facelessuser">Isaac Muse</a>

pages:
  - About RegReplace: index.md
  - Installation: installation.md
  - User Guide: usage.md
  - Contributing &amp; Support: contributing.md
  - License: license.md

theme: material
theme_dir: doc_theme

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: î…—
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - markdown.extensions.nl2br:
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.extra:
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.escapeall:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.plainhtml:
      strip_attributes: ''
  - pymdownx.snippets:
      base_path: docs/snippets

extra:
  palette:
    primary: blue
    accent: purple
  font:
    text: Roboto
    code: Roboto Mono
  social:
    - type: github
      link: https://github.com/facelessuser
extra_css:
  - extra.css
